networks:
  proxy:
    external: true
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 6969:3000
    networks:
      - proxy
    volumes:
      - ./config:/app/config
      # - /var/run/docker.sock:/var/run/docker.sock
      - /home/deds/homepage/logs:/app/logs
      - /mnt/arr/media:/mnt/arr/media
    environment:
      # PUID: ${PUID:-1000}
      # PGID: ${PGID:-1000}
      TZ: ${TZ:-UTC}
      HOMEPAGE_ALLOWED_HOSTS: '*'
      LOG_TARGETS: /app/logs/homepage.log
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.homepage-tailscale.entrypoints=web-secure
      - traefik.http.routers.homepage-tailscale.rule=Host(`${TAILNET}`)
      - traefik.http.routers.homepage-tailscale.tls.certresolver=vpnresolver
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - VOLUMES=1 # Allow access to viewing volumes
      - NETWORKS=1 # Allow access to viewing networks
      - IMAGES=1 # Allow access to viewing images
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 2375:2375
        # - 127.0.0.1:2375:2375

    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped

  internet-speed:
    image: germannewsmaker/myspeed
    container_name: myspeed
    ports:
      - 5216:5216
    networks:
      - proxy
    volumes:
      - /home/deds/myspeed/logs:/myspeed/data
    environment:
      TZ: ${TZ:-UTC}
    restart: unless-stopped
    labels:
      - homepage.group=Deployment
      - homepage.name=Internet Speed
      - homepage.icon=myspeed.png
      - homepage.href=http://home-ubuntu:5216
      - homepage.widget.type=myspeed
      - homepage.widget.url=http://myspeed:5216
